on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build web assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --prod
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: www
